### ISSUE TITLE
Migrate tests to pytest

### ISSUE THREAD

**Issue by readikus** [readikus/royston#24]
Straight forward hacktoberfest task to move the tests to pytest.

**Comment by gsilvapt** [comment]
Hey @readikus,

Wanted to take this issue which should be easy but cannot set the environment properly. I'm getting some errors in the tests and I hope you could help me out.

I create a new virtualenv, installed the requirements and simply ran `python3 -m unittest discover -p "*_test.py"`. Then I'm getting the following error:

```shell
======================================================================
ERROR: test_prune_old (tests.royston_prune_test.TestRoystonPrune)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/royston/tests/royston_prune_test.py", line 71, in test_prune_old
    r.prune()
  File "/royston/royston/royston.py", line 294, in prune
    self.ngram_history[ngram]['occurances'] = list(filter(is_in_range, self.ngram_history[ngram]['occurances']))
  File "/royston/royston/royston.py", line 289, in is_in_range
    return occurance['date'] >= self.options['history_start']
TypeError: can't compare offset-naive and offset-aware datetimes

----------------------------------------------------------------------
```

Do you recognize this output? is it safe to ignore and move on with this migration?

**Comment by readikus** [comment]
Hi, thank you - that would be awesome!!!

I have that fixed locally this morning - I’ve been trying to squash these for a while.

Have you tried running with the poetry script ‘poetry run test’?

**Comment by readikus** [comment]
@gsilvapt - just pushed a bunch of changes that fix the tests (it was a code issue).

**Comment by gsilvapt** [comment]
Thanks, @readikus. I ll pull and see ff that works. Aside from modified `self.assertEquals` to `assert x == y`, are there any other thing you would like to migrate?

**Comment by readikus** [comment]
Great question @gsilvapt

Please can we have a shared fixture for the share test data - i.e. time ranges, example docs etc.: https://github.com/readikus/royston/blob/45e74ef008d4b1d82933b334a9d6a4125b11f9d8/tests/royston_test.py#L16-L114 (this can be a separate PR, if you're after a quick hacktober PR :))

Maintain `poetry run test` and `poetry run coverage` commands. Ideally showing the coverage at the end of the `poetry run test` command would be great, but not essential.

Any issues trying to understand what the code is doing, let me know and I'll either update the code or docs.

**Comment by gsilvapt** [comment]
Sure, I can do the quick one because it is relatively straightforward. As for keeping the commands, I see `poetry` is running `coverage` to run tests. If you agree, I would change that to run pytest instead (while we're on it...) Moreover, seems there might be a `coverage` dependency as I'm getting a `command not found` error?

**Comment by readikus** [comment]
Superb work - I'll approve/merge on the 1st of Oct, so it counts towards hacktober :)
